# ACS 2018-2022 Census Tract Variables Education

This script is designed to automate the retrieval of American Community Survey (ACS) data for specific census tracts within Washington, D.C., across multiple years. By specifying the desired census boundaries (either 2010 or 2020 tracts) and ACS year, users can efficiently collect detailed demographic data for each tract, facilitating longitudinal analysis over time.

## Education Variables

https://data.census.gov/table/ACSST5Y2022.S1501?q=S1501:%20Educational%20Attainment&g=1400000US11001000101

`S1501_C01_002E: Population 18 to 24 years, Less than high school graduate`

`S1501_C01_003E: Population 18 to 24 years, High school graduate (includes equivalency)`

`S1501_C01_004E: Population 18 to 24 years, Some college or associate's degree`

`S1501_C01_005E: Population 18 to 24 years, Bachelor's degree or higher`

`S1501_C01_007E: Population 25 years and over, Less than 9th grade`

`S1501_C01_008E: Population 25 years and over, 9th to 12th grade, no diploma`

`S1501_C01_009E: Population 25 years and over, High school graduate (includes equivalency)`

`S1501_C01_010E: Population 25 years and over, Some college, no degree`

`S1501_C01_011E: Population 25 years and over, Associate's degree`

`S1501_C01_012E: Population 25 years and over, Bachelor's degree`

`S1501_C01_013E: Population 25 years and over, Graduate or professional degree`

In [ ]:
import requests
import pandas as pd

In [ ]:
# Your API key (make sure it's kept safe)
api_key = "1133bc6e7fa96d6cc28e4fce4958d2e67f760e4c"

### Census Tract Initializations for ACS Data

The lists `census_tracts_2020s` and `census_tracts_2010s` define the census tracts in Washington, D.C., for use in fetching data from the American Community Survey (ACS). These lists correspond to the census tracts used in the 2020 and 2010 Census data respectively. Each census tract represents a unique geographic area within the district and is identified by a specific code.

- **census_tracts_2020s**: This list includes the tract codes for the 2020 Census, which are used to retrieve ACS data corresponding to the 2020 census boundaries.
- **census_tracts_2010s**: This list includes the tract codes for the 2010 Census, allowing data retrieval based on 2010 census boundaries.

#### Usage:
These lists can be passed into functions that call the Census API to specify which tracts' data to fetch. Using these predefined lists ensures that data is collected consistently across different years, based on specific census boundaries.

In [ ]:
census_tracts_2020s = [
    '000101', '000102', '000201', '000202', '000300', '000400', '000501', '000502', '000600',
    '000702', '000703', '000704', '000802', '000803', '000804', '000902', '000903', '000904',
    '001002', '001003', '001004', '001100', '001200', '001301', '001303', '001304', '001401',
    '001402', '001500', '001600', '001702', '001803', '001804', '001901', '001902', '002001',
    '002002', '002101', '002102', '002201', '002202', '002301', '002302', '002400', '002501',
    '002503', '002504', '002600', '002702', '002703', '002704', '002801', '002802', '002900',
    '003000', '003100', '003200', '003301', '003302', '003400', '003500', '003600', '003701',
    '003702', '003801', '003802', '003901', '003902', '004001', '004002', '004100', '004201',
    '004202', '004300', '004401', '004402', '004600', '004702', '004703', '004704', '004801',
    '004802', '004901', '004902', '005001', '005003', '005004', '005202', '005203', '005302',
    '005303', '005501', '005502', '005503', '005601', '005602', '005801', '005802', '005900',
    '006400', '006500', '006600', '006700', '006801', '006802', '006804', '006900', '007000',
    '007100', '007201', '007202', '007203', '007301', '007304', '007401', '007403', '007404',
    '007406', '007407', '007408', '007409', '007502', '007503', '007504', '007601', '007603',
    '007604', '007605', '007703', '007707', '007708', '007709', '007803', '007804', '007806',
    '007807', '007808', '007809', '007901', '007903', '008001', '008002', '008100', '008200',
    '008301', '008302', '008402', '008410', '008701', '008702', '008802', '008803', '008804',
    '008903', '008904', '009000', '009102', '009201', '009203', '009204', '009301', '009302',
    '009400', '009503', '009504', '009505', '009507', '009508', '009509', '009510', '009511',
    '009601', '009602', '009603', '009604', '009700', '009801', '009802', '009803', '009804',
    '009807', '009810', '009811', '009901', '009902', '009903', '009904', '009905', '009906',
    '009907', '010100', '010201', '010202', '010300', '010400', '010500', '010601', '010602',
    '010603', '010700', '010800', '010900', '011001', '011002', '011100', '980000'
]

In [ ]:
census_tracts_2010s = [
    '000100', '000201', '000202', '000300', '000400', '000501', '000502', '000600',
    '000701', '000702', '000801', '000802', '000901', '000902', '001001', '001002',
    '001100', '001200', '001301', '001302', '001401', '001402', '001500', '001600',
    '001702', '001803', '001804', '001901', '001902', '002001', '002002', '002101',
    '002102', '002201', '002202', '002301', '002302', '002400', '002501', '002502',
    '002600', '002701', '002702', '002801', '002802', '002900', '003000', '003100',
    '003200', '003301', '003302', '003400', '003500', '003600', '003700', '003800',
    '003900', '004001', '004002', '004100', '004201', '004202', '004300', '004400',
    '004600', '004701', '004702', '004801', '004802', '004901', '004902', '005001',
    '005002', '005201', '005301', '005500', '005600', '005800', '005900', '006202',
    '006400', '006500', '006600', '006700', '006801', '006802', '006804', '006900',
    '007000', '007100', '007200', '007301', '007304', '007401', '007403', '007404',
    '007406', '007407', '007408', '007409', '007502', '007503', '007504', '007601',
    '007603', '007604', '007605', '007703', '007707', '007708', '007709', '007803',
    '007804', '007806', '007807', '007808', '007809', '007901', '007903', '008001',
    '008002', '008100', '008200', '008301', '008302', '008402', '008410', '008701',
    '008702', '008802', '008803', '008804', '008903', '008904', '009000', '009102',
    '009201', '009203', '009204', '009301', '009302', '009400', '009501', '009503',
    '009504', '009505', '009507', '009508', '009509', '009601', '009602', '009603',
    '009604', '009700', '009801', '009802', '009803', '009804', '009807', '009810',
    '009811', '009901', '009902', '009903', '009904', '009905', '009906', '009907',
    '010100', '010200', '010300', '010400', '010500', '010600', '010700', '010800',
    '010900', '011000', '011100'
]

### Function: `fetch_acs_data`

This function, `fetch_acs_data`, retrieves American Community Survey (ACS) data for a specified year, list of census tracts, and geographic area (defined by state and county FIPS codes). It sends a request to the Census API for each census tract provided, fetching specific demographic variables, and combines the results into a single DataFrame.

#### Parameters:
- **year** (str): The ACS data year (e.g., "2022").
- **census_tracts** (list): A list of census tracts to query.
- **api_key** (str): Your Census Bureau API key.
- **state** (str): State FIPS code, defaulted to "11" for Washington, D.C.
- **county** (str): County FIPS code, defaulted to "001" for Washington, D.C.

#### Returns:
- **DataFrame**: A pandas DataFrame containing ACS data for each specified census tract.

#### Important Notes:
The function currently retrieves the following variables:
- **Census Tract Name**
- **Population 18 to 24 years, Less than high school graduate** (`S1501_C01_002E`)
- **Population 18 to 24 years, High school graduate (includes equivalency)** (`S1501_C01_003E`)
- **Population 18 to 24 years, Some college or associate's degree** (`S1501_C01_004E`)
- **Population 18 to 24 years, Bachelor's degree or higher** (`S1501_C01_005E`)
- **Population 25 years and over, Less than 9th grade** (`S1501_C01_007E`)
- **Population 25 years and over, 9th to 12th grade, no diploma** (`S1501_C01_008E`)
- **Population 25 years and over, High school graduate (includes equivalency)** (`S1501_C01_009E`)
- **Population 25 years and over, Some college, no degree** (`S1501_C01_010E`)
- **Population 25 years and over, Associate's degree** (`S1501_C01_011E`)
- **Population 25 years and over, Bachelor's degree** (`S1501_C01_012E`)
- **Population 25 years and over, Graduate or professional degree** (`S1501_C01_013E`)

These variables are specified in the `variable_labels` dictionary. **If you want to retrieve different variables, you will need to update this dictionary and adjust the labels accordingly in the code.** This allows for customization based on the specific variables of interest in the ACS dataset.

In [ ]:
def fetch_acs_data(year, census_tracts, api_key, state="11", county="001"):
    """
    Fetch ACS data for a specified year, list of census tracts, state, and county.

    Parameters:
        year (str): The ACS data year (e.g., "2022").
        census_tracts (list): List of census tracts to fetch data for.
        api_key (str): API key for Census Bureau.
        state (str): State FIPS code. Default is "11" (Washington, D.C.).
        county (str): County FIPS code. Default is "001" (Washington, D.C.).

    Returns:
        DataFrame: DataFrame with ACS data for each census tract.
    """
    base_url = f"https://api.census.gov/data/{year}/acs/acs5/subject"

    # Variable mappings for better readability
    variable_labels = {
    "NAME": "Census Tract Name",
    "S1501_C01_002E": "Population 18 to 24 years, Less than high school graduate",
    "S1501_C01_003E": "Population 18 to 24 years, High school graduate (includes equivalency)",
    "S1501_C01_004E": "Population 18 to 24 years, Some college or associate's degree",
    "S1501_C01_005E": "Population 18 to 24 years, Bachelor's degree or higher",
    "S1501_C01_007E": "Population 25 years and over, Less than 9th grade",
    "S1501_C01_008E": "Population 25 years and over, 9th to 12th grade, no diploma",
    "S1501_C01_009E": "Population 25 years and over, High school graduate (includes equivalency)",
    "S1501_C01_010E": "Population 25 years and over, Some college, no degree",
    "S1501_C01_011E": "Population 25 years and over, Associate's degree",
    "S1501_C01_012E": "Population 25 years and over, Bachelor's degree",
    "S1501_C01_013E": "Population 25 years and over, Graduate or professional degree"
    }
    # Prepare an empty list to collect each tract's data
    data_list = []

    # Loop through each tract and make a request with progress tracking
    total_tracts = len(census_tracts)
    for idx, tract in enumerate(census_tracts, start=1):
        # Define parameters for the API request
        params = {
            "get": ",".join(variable_labels.keys()),  # Use the keys from variable_labels dictionary
            "for": f"tract:{tract}",                  # Specify each tract individually
            "in": f"state:{state} county:{county}",   # Specify state and county
            "key": api_key
        }

        # Send the request to the Census API
        response = requests.get(base_url, params=params)

        # Check if the response is successful
        if response.status_code == 200:
            data = response.json()[1:]  # Skip the header row
            data_list.extend(data)       # Append the data to the list
            print(f"Successfully fetched data for tract {tract} ({idx}/{total_tracts})")
        else:
            print(f"Error fetching data for tract {tract}: {response.status_code}")

    # Convert the collected data to a DataFrame with appropriate column names
    if data_list:
        columns = response.json()[0]  # Use the header row from the last successful response
        df = pd.DataFrame(data_list, columns=columns)

        # Rename columns with descriptive labels
        df = df.rename(columns=variable_labels)
    else:
        print("No data was fetched.")
        df = pd.DataFrame()  # Return an empty DataFrame if no data was fetched

    return df

## Fetching and Dislaying DC Census Tract Insurance Dataframes

# Fetching data for 2022

In [ ]:
# Fetching ACS data for the year 2022 for all census tracts listed in `census_tracts_2020s`
DC_CT_Education_2022 = fetch_acs_data(2022, census_tracts_2020s, api_key)

Successfully fetched data for tract 000101 (1/206)
Successfully fetched data for tract 000102 (2/206)
Successfully fetched data for tract 000201 (3/206)
Successfully fetched data for tract 000202 (4/206)
Successfully fetched data for tract 000300 (5/206)
Successfully fetched data for tract 000400 (6/206)
Successfully fetched data for tract 000501 (7/206)
Successfully fetched data for tract 000502 (8/206)
Successfully fetched data for tract 000600 (9/206)
Successfully fetched data for tract 000702 (10/206)
Successfully fetched data for tract 000703 (11/206)
Successfully fetched data for tract 000704 (12/206)
Successfully fetched data for tract 000802 (13/206)
Successfully fetched data for tract 000803 (14/206)
Successfully fetched data for tract 000804 (15/206)
Successfully fetched data for tract 000902 (16/206)
Successfully fetched data for tract 000903 (17/206)
Successfully fetched data for tract 000904 (18/206)
Successfully fetched data for tract 001002 (19/206)
Successfully fetched data for tract 001003 (20/206)
Successfully fetched data for tract 001004 (21/206)
Successfully fetched data for tract 001100 (22/206)
Successfully fetched data for tract 001200 (23/206)
Successfully fetched data for tract 001301 (24/206)
Successfully fetched data for tract 001303 (25/206)
Successfully fetched data for tract 001304 (26/206)
Successfully fetched data for tract 001401 (27/206)
Successfully fetched data for tract 001402 (28/206)
Successfully fetched data for tract 001500 (29/206)
Successfully fetched data for tract 001600 (30/206)
Successfully fetched data for tract 001702 (31/206)
Successfully fetched data for tract 001803 (32/206)
Successfully fetched data for tract 001804 (33/206)
Successfully fetched data for tract 001901 (34/206)
Successfully fetched data for tract 001902 (35/206)
Successfully fetched data for tract 002001 (36/206)
Successfully fetched data for tract 002002 (37/206)
Successfully fetched data for tract 002101 (38/206)
Successfully fetched data for tract 002102 (39/206)
Successfully fetched data for tract 002201 (40/206)
Successfully fetched data for tract 002202 (41/206)
Successfully fetched data for tract 002301 (42/206)
Successfully fetched data for tract 002302 (43/206)
Successfully fetched data for tract 002400 (44/206)
Successfully fetched data for tract 002501 (45/206)
Successfully fetched data for tract 002503 (46/206)
Successfully fetched data for tract 002504 (47/206)
Successfully fetched data for tract 002600 (48/206)
Successfully fetched data for tract 002702 (49/206)
Successfully fetched data for tract 002703 (50/206)
Successfully fetched data for tract 002704 (51/206)
Successfully fetched data for tract 002801 (52/206)
Successfully fetched data for tract 002802 (53/206)
Successfully fetched data for tract 002900 (54/206)
Successfully fetched data for tract 003000 (55/206)
Successfully fetched data for tract 003100 (56/206)
Successfully fetched data for tract 003200 (57/206)
Successfully fetched data for tract 003301 (58/206)
Successfully fetched data for tract 003302 (59/206)
Successfully fetched data for tract 003400 (60/206)
Successfully fetched data for tract 003500 (61/206)
Successfully fetched data for tract 003600 (62/206)
Successfully fetched data for tract 003701 (63/206)
Successfully fetched data for tract 003702 (64/206)
Successfully fetched data for tract 003801 (65/206)
Successfully fetched data for tract 003802 (66/206)
Successfully fetched data for tract 003901 (67/206)
Successfully fetched data for tract 003902 (68/206)
Successfully fetched data for tract 004001 (69/206)
Successfully fetched data for tract 004002 (70/206)
Successfully fetched data for tract 004100 (71/206)
Successfully fetched data for tract 004201 (72/206)
Successfully fetched data for tract 004202 (73/206)
Successfully fetched data for tract 004300 (74/206)
Successfully fetched data for tract 004401 (75/206)
Successfully fetched data for tract 004402 (76/206)
Successfully fetched data for tract 004600 (77/206)
Successfully fetched data for tract 004702 (78/206)
Successfully fetched data for tract 004703 (79/206)
Successfully fetched data for tract 004704 (80/206)
Successfully fetched data for tract 004801 (81/206)
Successfully fetched data for tract 004802 (82/206)
Successfully fetched data for tract 004901 (83/206)
Successfully fetched data for tract 004902 (84/206)
Successfully fetched data for tract 005001 (85/206)
Successfully fetched data for tract 005003 (86/206)
Successfully fetched data for tract 005004 (87/206)
Successfully fetched data for tract 005202 (88/206)
Successfully fetched data for tract 005203 (89/206)
Successfully fetched data for tract 005302 (90/206)
Successfully fetched data for tract 005303 (91/206)
Successfully fetched data for tract 005501 (92/206)
Successfully fetched data for tract 005502 (93/206)
Successfully fetched data for tract 005503 (94/206)
Successfully fetched data for tract 005601 (95/206)
Successfully fetched data for tract 005602 (96/206)
Successfully fetched data for tract 005801 (97/206)
Successfully fetched data for tract 005802 (98/206)
Successfully fetched data for tract 005900 (99/206)
Successfully fetched data for tract 006400 (100/206)
Successfully fetched data for tract 006500 (101/206)
Successfully fetched data for tract 006600 (102/206)
Successfully fetched data for tract 006700 (103/206)
Successfully fetched data for tract 006801 (104/206)
Successfully fetched data for tract 006802 (105/206)
Successfully fetched data for tract 006804 (106/206)
Successfully fetched data for tract 006900 (107/206)
Successfully fetched data for tract 007000 (108/206)
Successfully fetched data for tract 007100 (109/206)
Successfully fetched data for tract 007201 (110/206)
Successfully fetched data for tract 007202 (111/206)
Successfully fetched data for tract 007203 (112/206)
Successfully fetched data for tract 007301 (113/206)
Successfully fetched data for tract 007304 (114/206)
Successfully fetched data for tract 007401 (115/206)
Successfully fetched data for tract 007403 (116/206)
Successfully fetched data for tract 007404 (117/206)
Successfully fetched data for tract 007406 (118/206)
Successfully fetched data for tract 007407 (119/206)
Successfully fetched data for tract 007408 (120/206)
Successfully fetched data for tract 007409 (121/206)
Successfully fetched data for tract 007502 (122/206)
Successfully fetched data for tract 007503 (123/206)
Successfully fetched data for tract 007504 (124/206)
Successfully fetched data for tract 007601 (125/206)
Successfully fetched data for tract 007603 (126/206)
Successfully fetched data for tract 007604 (127/206)
Successfully fetched data for tract 007605 (128/206)
Successfully fetched data for tract 007703 (129/206)
Successfully fetched data for tract 007707 (130/206)
Successfully fetched data for tract 007708 (131/206)
Successfully fetched data for tract 007709 (132/206)
Successfully fetched data for tract 007803 (133/206)
Successfully fetched data for tract 007804 (134/206)
Successfully fetched data for tract 007806 (135/206)
Successfully fetched data for tract 007807 (136/206)
Successfully fetched data for tract 007808 (137/206)
Successfully fetched data for tract 007809 (138/206)
Successfully fetched data for tract 007901 (139/206)
Successfully fetched data for tract 007903 (140/206)
Successfully fetched data for tract 008001 (141/206)
Successfully fetched data for tract 008002 (142/206)
Successfully fetched data for tract 008100 (143/206)
Successfully fetched data for tract 008200 (144/206)
Successfully fetched data for tract 008301 (145/206)
Successfully fetched data for tract 008302 (146/206)
Successfully fetched data for tract 008402 (147/206)
Successfully fetched data for tract 008410 (148/206)
Successfully fetched data for tract 008701 (149/206)
Successfully fetched data for tract 008702 (150/206)
Successfully fetched data for tract 008802 (151/206)
Successfully fetched data for tract 008803 (152/206)
Successfully fetched data for tract 008804 (153/206)
Successfully fetched data for tract 008903 (154/206)
Successfully fetched data for tract 008904 (155/206)
Successfully fetched data for tract 009000 (156/206)
Successfully fetched data for tract 009102 (157/206)
Successfully fetched data for tract 009201 (158/206)
Successfully fetched data for tract 009203 (159/206)
Successfully fetched data for tract 009204 (160/206)
Successfully fetched data for tract 009301 (161/206)
Successfully fetched data for tract 009302 (162/206)
Successfully fetched data for tract 009400 (163/206)
Successfully fetched data for tract 009503 (164/206)
Successfully fetched data for tract 009504 (165/206)
Successfully fetched data for tract 009505 (166/206)
Successfully fetched data for tract 009507 (167/206)
Successfully fetched data for tract 009508 (168/206)
Successfully fetched data for tract 009509 (169/206)
Successfully fetched data for tract 009510 (170/206)
Successfully fetched data for tract 009511 (171/206)
Successfully fetched data for tract 009601 (172/206)
Successfully fetched data for tract 009602 (173/206)
Successfully fetched data for tract 009603 (174/206)
Successfully fetched data for tract 009604 (175/206)
Successfully fetched data for tract 009700 (176/206)
Successfully fetched data for tract 009801 (177/206)
Successfully fetched data for tract 009802 (178/206)
Successfully fetched data for tract 009803 (179/206)
Successfully fetched data for tract 009804 (180/206)
Successfully fetched data for tract 009807 (181/206)
Successfully fetched data for tract 009810 (182/206)
Successfully fetched data for tract 009811 (183/206)
Successfully fetched data for tract 009901 (184/206)
Successfully fetched data for tract 009902 (185/206)
Successfully fetched data for tract 009903 (186/206)
Successfully fetched data for tract 009904 (187/206)
Successfully fetched data for tract 009905 (188/206)
Successfully fetched data for tract 009906 (189/206)
Successfully fetched data for tract 009907 (190/206)
Successfully fetched data for tract 010100 (191/206)
Successfully fetched data for tract 010201 (192/206)
Successfully fetched data for tract 010202 (193/206)
Successfully fetched data for tract 010300 (194/206)
Successfully fetched data for tract 010400 (195/206)
Successfully fetched data for tract 010500 (196/206)
Successfully fetched data for tract 010601 (197/206)
Successfully fetched data for tract 010602 (198/206)
Successfully fetched data for tract 010603 (199/206)
Successfully fetched data for tract 010700 (200/206)
Successfully fetched data for tract 010800 (201/206)
Successfully fetched data for tract 010900 (202/206)
Successfully fetched data for tract 011001 (203/206)
Successfully fetched data for tract 011002 (204/206)
Successfully fetched data for tract 011100 (205/206)
Successfully fetched data for tract 980000 (206/206)

In [ ]:
# Displaying the final DataFrame `DC_CT_Education_2022` which contains 2022 ACS data
# for each specified census tract in Washington, D.C., including columns for
# census tract name and total population.

DC_CT_Education_2022.head(10)

,Census Tract Name,"Population 18 to 24 years, Less than high school graduate","Population 18 to 24 years, High school graduate (includes equivalency)","Population 18 to 24 years, Some college or associate's degree","Population 18 to 24 years, Bachelor's degree or higher","Population 25 years and over, Less than 9th grade","Population 25 years and over, 9th to 12th grade, no diploma","Population 25 years and over, High school graduate (includes equivalency)","Population 25 years and over, Some college, no degree","Population 25 years and over, Associate's degree","Population 25 years and over, Bachelor's degree","Population 25 years and over, Graduate or professional degree",state,county,tract
0,Census Tract 1.01; District of Columbia; Distr...,0,0,0,13,12,0,27,0,0,428,539,11,001,000101
1,Census Tract 1.02; District of Columbia; Distr...,0,4,18,48,60,0,48,143,27,1150,1328,11,001,000102
2,Census Tract 2.01; District of Columbia; Distr...,0,263,1986,30,0,0,12,0,4,30,32,11,001,000201
3,Census Tract 2.02; District of Columbia; Distr...,12,145,749,184,35,0,92,138,32,520,1754,11,001,000202
4,Census Tract 3; District of Columbia; District...,104,73,165,309,109,19,130,149,43,1015,2528,11,001,000300
5,Census Tract 4; District of Columbia; District...,19,40,4,35,16,21,20,35,38,376,729,11,001,000400
6,Census Tract 5.01; District of Columbia; Distr...,0,2,165,63,2,41,47,84,55,1011,1785,11,001,000501
7,Census Tract 5.02; District of Columbia; Distr...,0,15,12,81,15,28,55,138,18,646,1705,11,001,000502
8,Census Tract 6; District of Columbia; District...,0,18,17,29,68,102,160,234,0,958,2028,11,001,000600
9,Census Tract 7.02; District of Columbia; Distr...,0,0,55,119,0,0,65,292,15,785,1453,11,001,000702

# Fetching data for 2021

In [ ]:
# Fetching ACS data for the year 2021 for all census tracts listed in `census_tracts_2020s`
DC_CT_Education_2021 = fetch_acs_data(2021, census_tracts_2020s, api_key)

Successfully fetched data for tract 000101 (1/206)
Successfully fetched data for tract 000102 (2/206)
Successfully fetched data for tract 000201 (3/206)
Successfully fetched data for tract 000202 (4/206)
Successfully fetched data for tract 000300 (5/206)
Successfully fetched data for tract 000400 (6/206)
Successfully fetched data for tract 000501 (7/206)
Successfully fetched data for tract 000502 (8/206)
Successfully fetched data for tract 000600 (9/206)
Successfully fetched data for tract 000702 (10/206)
Successfully fetched data for tract 000703 (11/206)
Successfully fetched data for tract 000704 (12/206)
Successfully fetched data for tract 000802 (13/206)
Successfully fetched data for tract 000803 (14/206)
Successfully fetched data for tract 000804 (15/206)
Successfully fetched data for tract 000902 (16/206)
Successfully fetched data for tract 000903 (17/206)
Successfully fetched data for tract 000904 (18/206)
Successfully fetched data for tract 001002 (19/206)
Successfully fetched data for tract 001003 (20/206)
Successfully fetched data for tract 001004 (21/206)
Successfully fetched data for tract 001100 (22/206)
Successfully fetched data for tract 001200 (23/206)
Successfully fetched data for tract 001301 (24/206)
Successfully fetched data for tract 001303 (25/206)
Successfully fetched data for tract 001304 (26/206)
Successfully fetched data for tract 001401 (27/206)
Successfully fetched data for tract 001402 (28/206)
Successfully fetched data for tract 001500 (29/206)
Successfully fetched data for tract 001600 (30/206)
Successfully fetched data for tract 001702 (31/206)
Successfully fetched data for tract 001803 (32/206)
Successfully fetched data for tract 001804 (33/206)
Successfully fetched data for tract 001901 (34/206)
Successfully fetched data for tract 001902 (35/206)
Successfully fetched data for tract 002001 (36/206)
Successfully fetched data for tract 002002 (37/206)
Successfully fetched data for tract 002101 (38/206)
Successfully fetched data for tract 002102 (39/206)
Successfully fetched data for tract 002201 (40/206)
Successfully fetched data for tract 002202 (41/206)
Successfully fetched data for tract 002301 (42/206)
Successfully fetched data for tract 002302 (43/206)
Successfully fetched data for tract 002400 (44/206)
Successfully fetched data for tract 002501 (45/206)
Successfully fetched data for tract 002503 (46/206)
Successfully fetched data for tract 002504 (47/206)
Successfully fetched data for tract 002600 (48/206)
Successfully fetched data for tract 002702 (49/206)
Successfully fetched data for tract 002703 (50/206)
Successfully fetched data for tract 002704 (51/206)
Successfully fetched data for tract 002801 (52/206)
Successfully fetched data for tract 002802 (53/206)
Successfully fetched data for tract 002900 (54/206)
Successfully fetched data for tract 003000 (55/206)
Successfully fetched data for tract 003100 (56/206)
Successfully fetched data for tract 003200 (57/206)
Successfully fetched data for tract 003301 (58/206)
Successfully fetched data for tract 003302 (59/206)
Successfully fetched data for tract 003400 (60/206)
Successfully fetched data for tract 003500 (61/206)
Successfully fetched data for tract 003600 (62/206)
Successfully fetched data for tract 003701 (63/206)
Successfully fetched data for tract 003702 (64/206)
Successfully fetched data for tract 003801 (65/206)
Successfully fetched data for tract 003802 (66/206)
Successfully fetched data for tract 003901 (67/206)
Successfully fetched data for tract 003902 (68/206)
Successfully fetched data for tract 004001 (69/206)
Successfully fetched data for tract 004002 (70/206)
Successfully fetched data for tract 004100 (71/206)
Successfully fetched data for tract 004201 (72/206)
Successfully fetched data for tract 004202 (73/206)
Successfully fetched data for tract 004300 (74/206)
Successfully fetched data for tract 004401 (75/206)
Successfully fetched data for tract 004402 (76/206)
Successfully fetched data for tract 004600 (77/206)
Successfully fetched data for tract 004702 (78/206)
Successfully fetched data for tract 004703 (79/206)
Successfully fetched data for tract 004704 (80/206)
Successfully fetched data for tract 004801 (81/206)
Successfully fetched data for tract 004802 (82/206)
Successfully fetched data for tract 004901 (83/206)
Successfully fetched data for tract 004902 (84/206)
Successfully fetched data for tract 005001 (85/206)
Successfully fetched data for tract 005003 (86/206)
Successfully fetched data for tract 005004 (87/206)
Successfully fetched data for tract 005202 (88/206)
Successfully fetched data for tract 005203 (89/206)
Successfully fetched data for tract 005302 (90/206)
Successfully fetched data for tract 005303 (91/206)
Successfully fetched data for tract 005501 (92/206)
Successfully fetched data for tract 005502 (93/206)
Successfully fetched data for tract 005503 (94/206)
Successfully fetched data for tract 005601 (95/206)
Successfully fetched data for tract 005602 (96/206)
Successfully fetched data for tract 005801 (97/206)
Successfully fetched data for tract 005802 (98/206)
Successfully fetched data for tract 005900 (99/206)
Successfully fetched data for tract 006400 (100/206)
Successfully fetched data for tract 006500 (101/206)
Successfully fetched data for tract 006600 (102/206)
Successfully fetched data for tract 006700 (103/206)
Successfully fetched data for tract 006801 (104/206)
Successfully fetched data for tract 006802 (105/206)
Successfully fetched data for tract 006804 (106/206)
Successfully fetched data for tract 006900 (107/206)
Successfully fetched data for tract 007000 (108/206)
Successfully fetched data for tract 007100 (109/206)
Successfully fetched data for tract 007201 (110/206)
Successfully fetched data for tract 007202 (111/206)
Successfully fetched data for tract 007203 (112/206)
Successfully fetched data for tract 007301 (113/206)
Successfully fetched data for tract 007304 (114/206)
Successfully fetched data for tract 007401 (115/206)
Successfully fetched data for tract 007403 (116/206)
Successfully fetched data for tract 007404 (117/206)
Successfully fetched data for tract 007406 (118/206)
Successfully fetched data for tract 007407 (119/206)
Successfully fetched data for tract 007408 (120/206)
Successfully fetched data for tract 007409 (121/206)
Successfully fetched data for tract 007502 (122/206)
Successfully fetched data for tract 007503 (123/206)
Successfully fetched data for tract 007504 (124/206)
Successfully fetched data for tract 007601 (125/206)
Successfully fetched data for tract 007603 (126/206)
Successfully fetched data for tract 007604 (127/206)
Successfully fetched data for tract 007605 (128/206)
Successfully fetched data for tract 007703 (129/206)
Successfully fetched data for tract 007707 (130/206)
Successfully fetched data for tract 007708 (131/206)
Successfully fetched data for tract 007709 (132/206)
Successfully fetched data for tract 007803 (133/206)
Successfully fetched data for tract 007804 (134/206)
Successfully fetched data for tract 007806 (135/206)
Successfully fetched data for tract 007807 (136/206)
Successfully fetched data for tract 007808 (137/206)
Successfully fetched data for tract 007809 (138/206)
Successfully fetched data for tract 007901 (139/206)
Successfully fetched data for tract 007903 (140/206)
Successfully fetched data for tract 008001 (141/206)
Successfully fetched data for tract 008002 (142/206)
Successfully fetched data for tract 008100 (143/206)
Successfully fetched data for tract 008200 (144/206)
Successfully fetched data for tract 008301 (145/206)
Successfully fetched data for tract 008302 (146/206)
Successfully fetched data for tract 008402 (147/206)
Successfully fetched data for tract 008410 (148/206)
Successfully fetched data for tract 008701 (149/206)
Successfully fetched data for tract 008702 (150/206)
Successfully fetched data for tract 008802 (151/206)
Successfully fetched data for tract 008803 (152/206)
Successfully fetched data for tract 008804 (153/206)
Successfully fetched data for tract 008903 (154/206)
Successfully fetched data for tract 008904 (155/206)
Successfully fetched data for tract 009000 (156/206)
Successfully fetched data for tract 009102 (157/206)
Successfully fetched data for tract 009201 (158/206)
Successfully fetched data for tract 009203 (159/206)
Successfully fetched data for tract 009204 (160/206)
Successfully fetched data for tract 009301 (161/206)
Successfully fetched data for tract 009302 (162/206)
Successfully fetched data for tract 009400 (163/206)
Successfully fetched data for tract 009503 (164/206)
Successfully fetched data for tract 009504 (165/206)
Successfully fetched data for tract 009505 (166/206)
Successfully fetched data for tract 009507 (167/206)
Successfully fetched data for tract 009508 (168/206)
Successfully fetched data for tract 009509 (169/206)
Successfully fetched data for tract 009510 (170/206)
Successfully fetched data for tract 009511 (171/206)
Successfully fetched data for tract 009601 (172/206)
Successfully fetched data for tract 009602 (173/206)
Successfully fetched data for tract 009603 (174/206)
Successfully fetched data for tract 009604 (175/206)
Successfully fetched data for tract 009700 (176/206)
Successfully fetched data for tract 009801 (177/206)
Successfully fetched data for tract 009802 (178/206)
Successfully fetched data for tract 009803 (179/206)
Successfully fetched data for tract 009804 (180/206)
Successfully fetched data for tract 009807 (181/206)
Successfully fetched data for tract 009810 (182/206)
Successfully fetched data for tract 009811 (183/206)
Successfully fetched data for tract 009901 (184/206)
Successfully fetched data for tract 009902 (185/206)
Successfully fetched data for tract 009903 (186/206)
Successfully fetched data for tract 009904 (187/206)
Successfully fetched data for tract 009905 (188/206)
Successfully fetched data for tract 009906 (189/206)
Successfully fetched data for tract 009907 (190/206)
Successfully fetched data for tract 010100 (191/206)
Successfully fetched data for tract 010201 (192/206)
Successfully fetched data for tract 010202 (193/206)
Successfully fetched data for tract 010300 (194/206)
Successfully fetched data for tract 010400 (195/206)
Successfully fetched data for tract 010500 (196/206)
Successfully fetched data for tract 010601 (197/206)
Successfully fetched data for tract 010602 (198/206)
Successfully fetched data for tract 010603 (199/206)
Successfully fetched data for tract 010700 (200/206)
Successfully fetched data for tract 010800 (201/206)
Successfully fetched data for tract 010900 (202/206)
Successfully fetched data for tract 011001 (203/206)
Successfully fetched data for tract 011002 (204/206)
Successfully fetched data for tract 011100 (205/206)
Successfully fetched data for tract 980000 (206/206)

In [ ]:
# Displaying the final DataFrame `DC_CT_Education_2021` which contains 2021 ACS data
# for each specified census tract in Washington, D.C., including columns for
# census tract name and total population.

DC_CT_Education_2021.head(10)

,Census Tract Name,"Population 18 to 24 years, Less than high school graduate","Population 18 to 24 years, High school graduate (includes equivalency)","Population 18 to 24 years, Some college or associate's degree","Population 18 to 24 years, Bachelor's degree or higher","Population 25 years and over, Less than 9th grade","Population 25 years and over, 9th to 12th grade, no diploma","Population 25 years and over, High school graduate (includes equivalency)","Population 25 years and over, Some college, no degree","Population 25 years and over, Associate's degree","Population 25 years and over, Bachelor's degree","Population 25 years and over, Graduate or professional degree",state,county,tract
0,"Census Tract 1.01, District of Columbia, Distr...",0,0,0,28,9,0,20,56,0,583,482,11,001,000101
1,"Census Tract 1.02, District of Columbia, Distr...",10,6,12,40,79,0,86,97,0,1256,1306,11,001,000102
2,"Census Tract 2.01, District of Columbia, Distr...",0,616,3145,54,0,0,6,0,8,24,46,11,001,000201
3,"Census Tract 2.02, District of Columbia, Distr...",14,254,1093,172,16,0,92,239,20,598,1674,11,001,000202
4,"Census Tract 3, District of Columbia, District...",13,47,254,503,0,17,165,155,49,1260,2343,11,001,000300
5,"Census Tract 4, District of Columbia, District...",8,32,6,39,8,12,27,33,29,353,655,11,001,000400
6,"Census Tract 5.01, District of Columbia, Distr...",0,3,150,77,1,42,39,131,35,1039,1601,11,001,000501
7,"Census Tract 5.02, District of Columbia, Distr...",15,21,22,112,25,39,80,114,16,680,1743,11,001,000502
8,"Census Tract 6, District of Columbia, District...",0,33,28,145,88,106,204,227,0,1056,1955,11,001,000600
9,"Census Tract 7.02, District of Columbia, Distr...",0,0,37,90,0,25,72,286,26,632,1582,11,001,000702

# Fetching data for 2020

In [ ]:
# Fetching ACS data for the year 2020 for all census tracts listed in `census_tracts_2020s`
DC_CT_Education_2020 = fetch_acs_data(2020, census_tracts_2020s, api_key)

Successfully fetched data for tract 000101 (1/206)
Successfully fetched data for tract 000102 (2/206)
Successfully fetched data for tract 000201 (3/206)
Successfully fetched data for tract 000202 (4/206)
Successfully fetched data for tract 000300 (5/206)
Successfully fetched data for tract 000400 (6/206)
Successfully fetched data for tract 000501 (7/206)
Successfully fetched data for tract 000502 (8/206)
Successfully fetched data for tract 000600 (9/206)
Successfully fetched data for tract 000702 (10/206)
Successfully fetched data for tract 000703 (11/206)
Successfully fetched data for tract 000704 (12/206)
Successfully fetched data for tract 000802 (13/206)
Successfully fetched data for tract 000803 (14/206)
Successfully fetched data for tract 000804 (15/206)
Successfully fetched data for tract 000902 (16/206)
Successfully fetched data for tract 000903 (17/206)
Successfully fetched data for tract 000904 (18/206)
Successfully fetched data for tract 001002 (19/206)
Successfully fetched data for tract 001003 (20/206)
Successfully fetched data for tract 001004 (21/206)
Successfully fetched data for tract 001100 (22/206)
Successfully fetched data for tract 001200 (23/206)
Successfully fetched data for tract 001301 (24/206)
Successfully fetched data for tract 001303 (25/206)
Successfully fetched data for tract 001304 (26/206)
Successfully fetched data for tract 001401 (27/206)
Successfully fetched data for tract 001402 (28/206)
Successfully fetched data for tract 001500 (29/206)
Successfully fetched data for tract 001600 (30/206)
Successfully fetched data for tract 001702 (31/206)
Successfully fetched data for tract 001803 (32/206)
Successfully fetched data for tract 001804 (33/206)
Successfully fetched data for tract 001901 (34/206)
Successfully fetched data for tract 001902 (35/206)
Successfully fetched data for tract 002001 (36/206)
Successfully fetched data for tract 002002 (37/206)
Successfully fetched data for tract 002101 (38/206)
Successfully fetched data for tract 002102 (39/206)
Successfully fetched data for tract 002201 (40/206)
Successfully fetched data for tract 002202 (41/206)
Successfully fetched data for tract 002301 (42/206)
Successfully fetched data for tract 002302 (43/206)
Successfully fetched data for tract 002400 (44/206)
Successfully fetched data for tract 002501 (45/206)
Successfully fetched data for tract 002503 (46/206)
Successfully fetched data for tract 002504 (47/206)
Successfully fetched data for tract 002600 (48/206)
Successfully fetched data for tract 002702 (49/206)
Successfully fetched data for tract 002703 (50/206)
Successfully fetched data for tract 002704 (51/206)
Successfully fetched data for tract 002801 (52/206)
Successfully fetched data for tract 002802 (53/206)
Successfully fetched data for tract 002900 (54/206)
Successfully fetched data for tract 003000 (55/206)
Successfully fetched data for tract 003100 (56/206)
Successfully fetched data for tract 003200 (57/206)
Successfully fetched data for tract 003301 (58/206)
Successfully fetched data for tract 003302 (59/206)
Successfully fetched data for tract 003400 (60/206)
Successfully fetched data for tract 003500 (61/206)
Successfully fetched data for tract 003600 (62/206)
Successfully fetched data for tract 003701 (63/206)
Successfully fetched data for tract 003702 (64/206)
Successfully fetched data for tract 003801 (65/206)
Successfully fetched data for tract 003802 (66/206)
Successfully fetched data for tract 003901 (67/206)
Successfully fetched data for tract 003902 (68/206)
Successfully fetched data for tract 004001 (69/206)
Successfully fetched data for tract 004002 (70/206)
Successfully fetched data for tract 004100 (71/206)
Successfully fetched data for tract 004201 (72/206)
Successfully fetched data for tract 004202 (73/206)
Successfully fetched data for tract 004300 (74/206)
Successfully fetched data for tract 004401 (75/206)
Successfully fetched data for tract 004402 (76/206)
Successfully fetched data for tract 004600 (77/206)
Successfully fetched data for tract 004702 (78/206)
Successfully fetched data for tract 004703 (79/206)
Successfully fetched data for tract 004704 (80/206)
Successfully fetched data for tract 004801 (81/206)
Successfully fetched data for tract 004802 (82/206)
Successfully fetched data for tract 004901 (83/206)
Successfully fetched data for tract 004902 (84/206)
Successfully fetched data for tract 005001 (85/206)
Successfully fetched data for tract 005003 (86/206)
Successfully fetched data for tract 005004 (87/206)
Successfully fetched data for tract 005202 (88/206)
Successfully fetched data for tract 005203 (89/206)
Successfully fetched data for tract 005302 (90/206)
Successfully fetched data for tract 005303 (91/206)
Successfully fetched data for tract 005501 (92/206)
Successfully fetched data for tract 005502 (93/206)
Successfully fetched data for tract 005503 (94/206)
Successfully fetched data for tract 005601 (95/206)
Successfully fetched data for tract 005602 (96/206)
Successfully fetched data for tract 005801 (97/206)
Successfully fetched data for tract 005802 (98/206)
Successfully fetched data for tract 005900 (99/206)
Successfully fetched data for tract 006400 (100/206)
Successfully fetched data for tract 006500 (101/206)
Successfully fetched data for tract 006600 (102/206)
Successfully fetched data for tract 006700 (103/206)
Successfully fetched data for tract 006801 (104/206)
Successfully fetched data for tract 006802 (105/206)
Successfully fetched data for tract 006804 (106/206)
Successfully fetched data for tract 006900 (107/206)
Successfully fetched data for tract 007000 (108/206)
Successfully fetched data for tract 007100 (109/206)
Successfully fetched data for tract 007201 (110/206)
Successfully fetched data for tract 007202 (111/206)
Successfully fetched data for tract 007203 (112/206)
Successfully fetched data for tract 007301 (113/206)
Successfully fetched data for tract 007304 (114/206)
Successfully fetched data for tract 007401 (115/206)
Successfully fetched data for tract 007403 (116/206)
Successfully fetched data for tract 007404 (117/206)
Successfully fetched data for tract 007406 (118/206)
Successfully fetched data for tract 007407 (119/206)
Successfully fetched data for tract 007408 (120/206)
Successfully fetched data for tract 007409 (121/206)
Successfully fetched data for tract 007502 (122/206)
Successfully fetched data for tract 007503 (123/206)
Successfully fetched data for tract 007504 (124/206)
Successfully fetched data for tract 007601 (125/206)
Successfully fetched data for tract 007603 (126/206)
Successfully fetched data for tract 007604 (127/206)
Successfully fetched data for tract 007605 (128/206)
Successfully fetched data for tract 007703 (129/206)
Successfully fetched data for tract 007707 (130/206)
Successfully fetched data for tract 007708 (131/206)
Successfully fetched data for tract 007709 (132/206)
Successfully fetched data for tract 007803 (133/206)
Successfully fetched data for tract 007804 (134/206)
Successfully fetched data for tract 007806 (135/206)
Successfully fetched data for tract 007807 (136/206)
Successfully fetched data for tract 007808 (137/206)
Successfully fetched data for tract 007809 (138/206)
Successfully fetched data for tract 007901 (139/206)
Successfully fetched data for tract 007903 (140/206)
Successfully fetched data for tract 008001 (141/206)
Successfully fetched data for tract 008002 (142/206)
Successfully fetched data for tract 008100 (143/206)
Successfully fetched data for tract 008200 (144/206)
Successfully fetched data for tract 008301 (145/206)
Successfully fetched data for tract 008302 (146/206)
Successfully fetched data for tract 008402 (147/206)
Successfully fetched data for tract 008410 (148/206)
Successfully fetched data for tract 008701 (149/206)
Successfully fetched data for tract 008702 (150/206)
Successfully fetched data for tract 008802 (151/206)
Successfully fetched data for tract 008803 (152/206)
Successfully fetched data for tract 008804 (153/206)
Successfully fetched data for tract 008903 (154/206)
Successfully fetched data for tract 008904 (155/206)
Successfully fetched data for tract 009000 (156/206)
Successfully fetched data for tract 009102 (157/206)
Successfully fetched data for tract 009201 (158/206)
Successfully fetched data for tract 009203 (159/206)
Successfully fetched data for tract 009204 (160/206)
Successfully fetched data for tract 009301 (161/206)
Successfully fetched data for tract 009302 (162/206)
Successfully fetched data for tract 009400 (163/206)
Successfully fetched data for tract 009503 (164/206)
Successfully fetched data for tract 009504 (165/206)
Successfully fetched data for tract 009505 (166/206)
Successfully fetched data for tract 009507 (167/206)
Successfully fetched data for tract 009508 (168/206)
Successfully fetched data for tract 009509 (169/206)
Successfully fetched data for tract 009510 (170/206)
Successfully fetched data for tract 009511 (171/206)
Successfully fetched data for tract 009601 (172/206)
Successfully fetched data for tract 009602 (173/206)
Successfully fetched data for tract 009603 (174/206)
Successfully fetched data for tract 009604 (175/206)
Successfully fetched data for tract 009700 (176/206)
Successfully fetched data for tract 009801 (177/206)
Successfully fetched data for tract 009802 (178/206)
Successfully fetched data for tract 009803 (179/206)
Successfully fetched data for tract 009804 (180/206)
Successfully fetched data for tract 009807 (181/206)
Successfully fetched data for tract 009810 (182/206)
Successfully fetched data for tract 009811 (183/206)
Successfully fetched data for tract 009901 (184/206)
Successfully fetched data for tract 009902 (185/206)
Successfully fetched data for tract 009903 (186/206)
Successfully fetched data for tract 009904 (187/206)
Successfully fetched data for tract 009905 (188/206)
Successfully fetched data for tract 009906 (189/206)
Successfully fetched data for tract 009907 (190/206)
Successfully fetched data for tract 010100 (191/206)
Successfully fetched data for tract 010201 (192/206)
Successfully fetched data for tract 010202 (193/206)
Successfully fetched data for tract 010300 (194/206)
Successfully fetched data for tract 010400 (195/206)
Successfully fetched data for tract 010500 (196/206)
Successfully fetched data for tract 010601 (197/206)
Successfully fetched data for tract 010602 (198/206)
Successfully fetched data for tract 010603 (199/206)
Successfully fetched data for tract 010700 (200/206)
Successfully fetched data for tract 010800 (201/206)
Successfully fetched data for tract 010900 (202/206)
Successfully fetched data for tract 011001 (203/206)
Successfully fetched data for tract 011002 (204/206)
Successfully fetched data for tract 011100 (205/206)
Successfully fetched data for tract 980000 (206/206)

In [ ]:
# Displaying the final DataFrame `DC_CT_Education_2020` which contains 2020 ACS data
# for each specified census tract in Washington, D.C., including columns for
# census tract name and total population.

DC_CT_Education_2020.head(10)

,Census Tract Name,"Population 18 to 24 years, Less than high school graduate","Population 18 to 24 years, High school graduate (includes equivalency)","Population 18 to 24 years, Some college or associate's degree","Population 18 to 24 years, Bachelor's degree or higher","Population 25 years and over, Less than 9th grade","Population 25 years and over, 9th to 12th grade, no diploma","Population 25 years and over, High school graduate (includes equivalency)","Population 25 years and over, Some college, no degree","Population 25 years and over, Associate's degree","Population 25 years and over, Bachelor's degree","Population 25 years and over, Graduate or professional degree",state,county,tract
0,"Census Tract 1.01, District of Columbia, Distr...",0,0,0,48,23,0,36,52,0,531,444,11,001,000101
1,"Census Tract 1.02, District of Columbia, Distr...",7,4,27,39,52,0,100,112,0,1114,1534,11,001,000102
2,"Census Tract 2.01, District of Columbia, Distr...",0,678,3097,47,0,0,6,0,7,24,50,11,001,000201
3,"Census Tract 2.02, District of Columbia, Distr...",21,208,1077,140,15,0,53,260,29,817,1780,11,001,000202
4,"Census Tract 3, District of Columbia, District...",20,69,220,662,0,4,160,162,51,1549,2455,11,001,000300
5,"Census Tract 4, District of Columbia, District...",10,4,9,32,92,0,39,47,14,269,710,11,001,000400
6,"Census Tract 5.01, District of Columbia, Distr...",0,4,32,70,1,36,39,134,75,1119,1530,11,001,000501
7,"Census Tract 5.02, District of Columbia, Distr...",4,20,27,117,8,19,121,160,24,672,1762,11,001,000502
8,"Census Tract 6, District of Columbia, District...",0,41,61,252,87,114,173,270,0,1123,1871,11,001,000600
9,"Census Tract 7.02, District of Columbia, Distr...",8,0,51,65,12,99,128,294,13,649,1513,11,001,000702

# Fetching data for 2019

In [ ]:
# Fetching ACS data for the year 2019 for all census tracts listed in `census_tracts_2010s`
DC_CT_Education_2019 = fetch_acs_data(2019, census_tracts_2010s, api_key)

Successfully fetched data for tract 000100 (1/179)
Successfully fetched data for tract 000201 (2/179)
Successfully fetched data for tract 000202 (3/179)
Successfully fetched data for tract 000300 (4/179)
Successfully fetched data for tract 000400 (5/179)
Successfully fetched data for tract 000501 (6/179)
Successfully fetched data for tract 000502 (7/179)
Successfully fetched data for tract 000600 (8/179)
Successfully fetched data for tract 000701 (9/179)
Successfully fetched data for tract 000702 (10/179)
Successfully fetched data for tract 000801 (11/179)
Successfully fetched data for tract 000802 (12/179)
Successfully fetched data for tract 000901 (13/179)
Successfully fetched data for tract 000902 (14/179)
Successfully fetched data for tract 001001 (15/179)
Successfully fetched data for tract 001002 (16/179)
Successfully fetched data for tract 001100 (17/179)
Successfully fetched data for tract 001200 (18/179)
Successfully fetched data for tract 001301 (19/179)
Successfully fetched data for tract 001302 (20/179)
Successfully fetched data for tract 001401 (21/179)
Successfully fetched data for tract 001402 (22/179)
Successfully fetched data for tract 001500 (23/179)
Successfully fetched data for tract 001600 (24/179)
Successfully fetched data for tract 001702 (25/179)
Successfully fetched data for tract 001803 (26/179)
Successfully fetched data for tract 001804 (27/179)
Successfully fetched data for tract 001901 (28/179)
Successfully fetched data for tract 001902 (29/179)
Successfully fetched data for tract 002001 (30/179)
Successfully fetched data for tract 002002 (31/179)
Successfully fetched data for tract 002101 (32/179)
Successfully fetched data for tract 002102 (33/179)
Successfully fetched data for tract 002201 (34/179)
Successfully fetched data for tract 002202 (35/179)
Successfully fetched data for tract 002301 (36/179)
Successfully fetched data for tract 002302 (37/179)
Successfully fetched data for tract 002400 (38/179)
Successfully fetched data for tract 002501 (39/179)
Successfully fetched data for tract 002502 (40/179)
Successfully fetched data for tract 002600 (41/179)
Successfully fetched data for tract 002701 (42/179)
Successfully fetched data for tract 002702 (43/179)
Successfully fetched data for tract 002801 (44/179)
Successfully fetched data for tract 002802 (45/179)
Successfully fetched data for tract 002900 (46/179)
Successfully fetched data for tract 003000 (47/179)
Successfully fetched data for tract 003100 (48/179)
Successfully fetched data for tract 003200 (49/179)
Successfully fetched data for tract 003301 (50/179)
Successfully fetched data for tract 003302 (51/179)
Successfully fetched data for tract 003400 (52/179)
Successfully fetched data for tract 003500 (53/179)
Successfully fetched data for tract 003600 (54/179)
Successfully fetched data for tract 003700 (55/179)
Successfully fetched data for tract 003800 (56/179)
Successfully fetched data for tract 003900 (57/179)
Successfully fetched data for tract 004001 (58/179)
Successfully fetched data for tract 004002 (59/179)
Successfully fetched data for tract 004100 (60/179)
Successfully fetched data for tract 004201 (61/179)
Successfully fetched data for tract 004202 (62/179)
Successfully fetched data for tract 004300 (63/179)
Successfully fetched data for tract 004400 (64/179)
Successfully fetched data for tract 004600 (65/179)
Successfully fetched data for tract 004701 (66/179)
Successfully fetched data for tract 004702 (67/179)
Successfully fetched data for tract 004801 (68/179)
Successfully fetched data for tract 004802 (69/179)
Successfully fetched data for tract 004901 (70/179)
Successfully fetched data for tract 004902 (71/179)
Successfully fetched data for tract 005001 (72/179)
Successfully fetched data for tract 005002 (73/179)
Successfully fetched data for tract 005201 (74/179)
Successfully fetched data for tract 005301 (75/179)
Successfully fetched data for tract 005500 (76/179)
Successfully fetched data for tract 005600 (77/179)
Successfully fetched data for tract 005800 (78/179)
Successfully fetched data for tract 005900 (79/179)
Successfully fetched data for tract 006202 (80/179)
Successfully fetched data for tract 006400 (81/179)
Successfully fetched data for tract 006500 (82/179)
Successfully fetched data for tract 006600 (83/179)
Successfully fetched data for tract 006700 (84/179)
Successfully fetched data for tract 006801 (85/179)
Successfully fetched data for tract 006802 (86/179)
Successfully fetched data for tract 006804 (87/179)
Successfully fetched data for tract 006900 (88/179)
Successfully fetched data for tract 007000 (89/179)
Successfully fetched data for tract 007100 (90/179)
Successfully fetched data for tract 007200 (91/179)
Successfully fetched data for tract 007301 (92/179)
Successfully fetched data for tract 007304 (93/179)
Successfully fetched data for tract 007401 (94/179)
Successfully fetched data for tract 007403 (95/179)
Successfully fetched data for tract 007404 (96/179)
Successfully fetched data for tract 007406 (97/179)
Successfully fetched data for tract 007407 (98/179)
Successfully fetched data for tract 007408 (99/179)
Successfully fetched data for tract 007409 (100/179)
Successfully fetched data for tract 007502 (101/179)
Successfully fetched data for tract 007503 (102/179)
Successfully fetched data for tract 007504 (103/179)
Successfully fetched data for tract 007601 (104/179)
Successfully fetched data for tract 007603 (105/179)
Successfully fetched data for tract 007604 (106/179)
Successfully fetched data for tract 007605 (107/179)
Successfully fetched data for tract 007703 (108/179)
Successfully fetched data for tract 007707 (109/179)
Successfully fetched data for tract 007708 (110/179)
Successfully fetched data for tract 007709 (111/179)
Successfully fetched data for tract 007803 (112/179)
Successfully fetched data for tract 007804 (113/179)
Successfully fetched data for tract 007806 (114/179)
Successfully fetched data for tract 007807 (115/179)
Successfully fetched data for tract 007808 (116/179)
Successfully fetched data for tract 007809 (117/179)
Successfully fetched data for tract 007901 (118/179)
Successfully fetched data for tract 007903 (119/179)
Successfully fetched data for tract 008001 (120/179)
Successfully fetched data for tract 008002 (121/179)
Successfully fetched data for tract 008100 (122/179)
Successfully fetched data for tract 008200 (123/179)
Successfully fetched data for tract 008301 (124/179)
Successfully fetched data for tract 008302 (125/179)
Successfully fetched data for tract 008402 (126/179)
Successfully fetched data for tract 008410 (127/179)
Successfully fetched data for tract 008701 (128/179)
Successfully fetched data for tract 008702 (129/179)
Successfully fetched data for tract 008802 (130/179)
Successfully fetched data for tract 008803 (131/179)
Successfully fetched data for tract 008804 (132/179)
Successfully fetched data for tract 008903 (133/179)
Successfully fetched data for tract 008904 (134/179)
Successfully fetched data for tract 009000 (135/179)
Successfully fetched data for tract 009102 (136/179)
Successfully fetched data for tract 009201 (137/179)
Successfully fetched data for tract 009203 (138/179)
Successfully fetched data for tract 009204 (139/179)
Successfully fetched data for tract 009301 (140/179)
Successfully fetched data for tract 009302 (141/179)
Successfully fetched data for tract 009400 (142/179)
Successfully fetched data for tract 009501 (143/179)
Successfully fetched data for tract 009503 (144/179)
Successfully fetched data for tract 009504 (145/179)
Successfully fetched data for tract 009505 (146/179)
Successfully fetched data for tract 009507 (147/179)
Successfully fetched data for tract 009508 (148/179)
Successfully fetched data for tract 009509 (149/179)
Successfully fetched data for tract 009601 (150/179)
Successfully fetched data for tract 009602 (151/179)
Successfully fetched data for tract 009603 (152/179)
Successfully fetched data for tract 009604 (153/179)
Successfully fetched data for tract 009700 (154/179)
Successfully fetched data for tract 009801 (155/179)
Successfully fetched data for tract 009802 (156/179)
Successfully fetched data for tract 009803 (157/179)
Successfully fetched data for tract 009804 (158/179)
Successfully fetched data for tract 009807 (159/179)
Successfully fetched data for tract 009810 (160/179)
Successfully fetched data for tract 009811 (161/179)
Successfully fetched data for tract 009901 (162/179)
Successfully fetched data for tract 009902 (163/179)
Successfully fetched data for tract 009903 (164/179)
Successfully fetched data for tract 009904 (165/179)
Successfully fetched data for tract 009905 (166/179)
Successfully fetched data for tract 009906 (167/179)
Successfully fetched data for tract 009907 (168/179)
Successfully fetched data for tract 010100 (169/179)
Successfully fetched data for tract 010200 (170/179)
Successfully fetched data for tract 010300 (171/179)
Successfully fetched data for tract 010400 (172/179)
Successfully fetched data for tract 010500 (173/179)
Successfully fetched data for tract 010600 (174/179)
Successfully fetched data for tract 010700 (175/179)
Successfully fetched data for tract 010800 (176/179)
Successfully fetched data for tract 010900 (177/179)
Successfully fetched data for tract 011000 (178/179)
Successfully fetched data for tract 011100 (179/179)

In [ ]:
# Displaying the final DataFrame `DC_CT_Education_2019` which contains 2019 ACS data
# for each specified census tract in Washington, D.C., including columns for
# census tract name and total population.

DC_CT_Education_2019.head(10)

,Census Tract Name,"Population 18 to 24 years, Less than high school graduate","Population 18 to 24 years, High school graduate (includes equivalency)","Population 18 to 24 years, Some college or associate's degree","Population 18 to 24 years, Bachelor's degree or higher","Population 25 years and over, Less than 9th grade","Population 25 years and over, 9th to 12th grade, no diploma","Population 25 years and over, High school graduate (includes equivalency)","Population 25 years and over, Some college, no degree","Population 25 years and over, Associate's degree","Population 25 years and over, Bachelor's degree","Population 25 years and over, Graduate or professional degree",state,county,tract
0,"Census Tract 1, District of Columbia, District...",4,7,125,160,118,0,163,137,0,1304,2248,11,001,000100
1,"Census Tract 2.01, District of Columbia, Distr...",0,700,3052,31,0,0,4,0,0,22,46,11,001,000201
2,"Census Tract 2.02, District of Columbia, Distr...",20,172,1403,147,14,0,8,231,35,764,1568,11,001,000202
3,"Census Tract 3, District of Columbia, District...",20,74,424,656,0,29,153,154,72,1556,2422,11,001,000300
4,"Census Tract 4, District of Columbia, District...",6,5,8,36,79,0,50,58,17,333,577,11,001,000400
5,"Census Tract 5.01, District of Columbia, Distr...",0,3,33,96,1,40,43,165,60,793,1783,11,001,000501
6,"Census Tract 5.02, District of Columbia, Distr...",15,20,32,102,8,12,93,133,35,817,1663,11,001,000502
7,"Census Tract 6, District of Columbia, District...",0,60,81,219,112,101,190,170,12,1041,2243,11,001,000600
8,"Census Tract 7.01, District of Columbia, Distr...",27,55,236,206,43,1,126,188,0,1333,3024,11,001,000701
9,"Census Tract 7.02, District of Columbia, Distr...",3,0,159,106,24,117,163,312,15,623,1331,11,001,000702

# Fetching data for 2018

In [ ]:
# Fetching ACS data for the year 2018 for all census tracts listed in `census_tracts_2010s`
DC_CT_Education_2018 = fetch_acs_data(2018, census_tracts_2010s, api_key)

Successfully fetched data for tract 000100 (1/179)
Successfully fetched data for tract 000201 (2/179)
Successfully fetched data for tract 000202 (3/179)
Successfully fetched data for tract 000300 (4/179)
Successfully fetched data for tract 000400 (5/179)
Successfully fetched data for tract 000501 (6/179)
Successfully fetched data for tract 000502 (7/179)
Successfully fetched data for tract 000600 (8/179)
Successfully fetched data for tract 000701 (9/179)
Successfully fetched data for tract 000702 (10/179)
Successfully fetched data for tract 000801 (11/179)
Successfully fetched data for tract 000802 (12/179)
Successfully fetched data for tract 000901 (13/179)
Successfully fetched data for tract 000902 (14/179)
Successfully fetched data for tract 001001 (15/179)
Successfully fetched data for tract 001002 (16/179)
Successfully fetched data for tract 001100 (17/179)
Successfully fetched data for tract 001200 (18/179)
Successfully fetched data for tract 001301 (19/179)
Successfully fetched data for tract 001302 (20/179)
Successfully fetched data for tract 001401 (21/179)
Successfully fetched data for tract 001402 (22/179)
Successfully fetched data for tract 001500 (23/179)
Successfully fetched data for tract 001600 (24/179)
Successfully fetched data for tract 001702 (25/179)
Successfully fetched data for tract 001803 (26/179)
Successfully fetched data for tract 001804 (27/179)
Successfully fetched data for tract 001901 (28/179)
Successfully fetched data for tract 001902 (29/179)
Successfully fetched data for tract 002001 (30/179)
Successfully fetched data for tract 002002 (31/179)
Successfully fetched data for tract 002101 (32/179)
Successfully fetched data for tract 002102 (33/179)
Successfully fetched data for tract 002201 (34/179)
Successfully fetched data for tract 002202 (35/179)
Successfully fetched data for tract 002301 (36/179)
Successfully fetched data for tract 002302 (37/179)
Successfully fetched data for tract 002400 (38/179)
Successfully fetched data for tract 002501 (39/179)
Successfully fetched data for tract 002502 (40/179)
Successfully fetched data for tract 002600 (41/179)
Successfully fetched data for tract 002701 (42/179)
Successfully fetched data for tract 002702 (43/179)
Successfully fetched data for tract 002801 (44/179)
Successfully fetched data for tract 002802 (45/179)
Successfully fetched data for tract 002900 (46/179)
Successfully fetched data for tract 003000 (47/179)
Successfully fetched data for tract 003100 (48/179)
Successfully fetched data for tract 003200 (49/179)
Successfully fetched data for tract 003301 (50/179)
Successfully fetched data for tract 003302 (51/179)
Successfully fetched data for tract 003400 (52/179)
Successfully fetched data for tract 003500 (53/179)
Successfully fetched data for tract 003600 (54/179)
Successfully fetched data for tract 003700 (55/179)
Successfully fetched data for tract 003800 (56/179)
Successfully fetched data for tract 003900 (57/179)
Successfully fetched data for tract 004001 (58/179)
Successfully fetched data for tract 004002 (59/179)
Successfully fetched data for tract 004100 (60/179)
Successfully fetched data for tract 004201 (61/179)
Successfully fetched data for tract 004202 (62/179)
Successfully fetched data for tract 004300 (63/179)
Successfully fetched data for tract 004400 (64/179)
Successfully fetched data for tract 004600 (65/179)
Successfully fetched data for tract 004701 (66/179)
Successfully fetched data for tract 004702 (67/179)
Successfully fetched data for tract 004801 (68/179)
Successfully fetched data for tract 004802 (69/179)
Successfully fetched data for tract 004901 (70/179)
Successfully fetched data for tract 004902 (71/179)
Successfully fetched data for tract 005001 (72/179)
Successfully fetched data for tract 005002 (73/179)
Successfully fetched data for tract 005201 (74/179)
Successfully fetched data for tract 005301 (75/179)
Successfully fetched data for tract 005500 (76/179)
Successfully fetched data for tract 005600 (77/179)
Successfully fetched data for tract 005800 (78/179)
Successfully fetched data for tract 005900 (79/179)
Successfully fetched data for tract 006202 (80/179)
Successfully fetched data for tract 006400 (81/179)
Successfully fetched data for tract 006500 (82/179)
Successfully fetched data for tract 006600 (83/179)
Successfully fetched data for tract 006700 (84/179)
Successfully fetched data for tract 006801 (85/179)
Successfully fetched data for tract 006802 (86/179)
Successfully fetched data for tract 006804 (87/179)
Successfully fetched data for tract 006900 (88/179)
Successfully fetched data for tract 007000 (89/179)
Successfully fetched data for tract 007100 (90/179)
Successfully fetched data for tract 007200 (91/179)
Successfully fetched data for tract 007301 (92/179)
Successfully fetched data for tract 007304 (93/179)
Successfully fetched data for tract 007401 (94/179)
Successfully fetched data for tract 007403 (95/179)
Successfully fetched data for tract 007404 (96/179)
Successfully fetched data for tract 007406 (97/179)
Successfully fetched data for tract 007407 (98/179)
Successfully fetched data for tract 007408 (99/179)
Successfully fetched data for tract 007409 (100/179)
Successfully fetched data for tract 007502 (101/179)
Successfully fetched data for tract 007503 (102/179)
Successfully fetched data for tract 007504 (103/179)
Successfully fetched data for tract 007601 (104/179)
Successfully fetched data for tract 007603 (105/179)
Successfully fetched data for tract 007604 (106/179)
Successfully fetched data for tract 007605 (107/179)
Successfully fetched data for tract 007703 (108/179)
Successfully fetched data for tract 007707 (109/179)
Successfully fetched data for tract 007708 (110/179)
Successfully fetched data for tract 007709 (111/179)
Successfully fetched data for tract 007803 (112/179)
Successfully fetched data for tract 007804 (113/179)
Successfully fetched data for tract 007806 (114/179)
Successfully fetched data for tract 007807 (115/179)
Successfully fetched data for tract 007808 (116/179)
Successfully fetched data for tract 007809 (117/179)
Successfully fetched data for tract 007901 (118/179)
Successfully fetched data for tract 007903 (119/179)
Successfully fetched data for tract 008001 (120/179)
Successfully fetched data for tract 008002 (121/179)
Successfully fetched data for tract 008100 (122/179)
Successfully fetched data for tract 008200 (123/179)
Successfully fetched data for tract 008301 (124/179)
Successfully fetched data for tract 008302 (125/179)
Successfully fetched data for tract 008402 (126/179)
Successfully fetched data for tract 008410 (127/179)
Successfully fetched data for tract 008701 (128/179)
Successfully fetched data for tract 008702 (129/179)
Successfully fetched data for tract 008802 (130/179)
Successfully fetched data for tract 008803 (131/179)
Successfully fetched data for tract 008804 (132/179)
Successfully fetched data for tract 008903 (133/179)
Successfully fetched data for tract 008904 (134/179)
Successfully fetched data for tract 009000 (135/179)
Successfully fetched data for tract 009102 (136/179)
Successfully fetched data for tract 009201 (137/179)
Successfully fetched data for tract 009203 (138/179)
Successfully fetched data for tract 009204 (139/179)
Successfully fetched data for tract 009301 (140/179)
Successfully fetched data for tract 009302 (141/179)
Successfully fetched data for tract 009400 (142/179)
Successfully fetched data for tract 009501 (143/179)
Successfully fetched data for tract 009503 (144/179)
Successfully fetched data for tract 009504 (145/179)
Successfully fetched data for tract 009505 (146/179)
Successfully fetched data for tract 009507 (147/179)
Successfully fetched data for tract 009508 (148/179)
Successfully fetched data for tract 009509 (149/179)
Successfully fetched data for tract 009601 (150/179)
Successfully fetched data for tract 009602 (151/179)
Successfully fetched data for tract 009603 (152/179)
Successfully fetched data for tract 009604 (153/179)
Successfully fetched data for tract 009700 (154/179)
Successfully fetched data for tract 009801 (155/179)
Successfully fetched data for tract 009802 (156/179)
Successfully fetched data for tract 009803 (157/179)
Successfully fetched data for tract 009804 (158/179)
Successfully fetched data for tract 009807 (159/179)
Successfully fetched data for tract 009810 (160/179)
Successfully fetched data for tract 009811 (161/179)
Successfully fetched data for tract 009901 (162/179)
Successfully fetched data for tract 009902 (163/179)
Successfully fetched data for tract 009903 (164/179)
Successfully fetched data for tract 009904 (165/179)
Successfully fetched data for tract 009905 (166/179)
Successfully fetched data for tract 009906 (167/179)
Successfully fetched data for tract 009907 (168/179)
Successfully fetched data for tract 010100 (169/179)
Successfully fetched data for tract 010200 (170/179)
Successfully fetched data for tract 010300 (171/179)
Successfully fetched data for tract 010400 (172/179)
Successfully fetched data for tract 010500 (173/179)
Successfully fetched data for tract 010600 (174/179)
Successfully fetched data for tract 010700 (175/179)
Successfully fetched data for tract 010800 (176/179)
Successfully fetched data for tract 010900 (177/179)
Successfully fetched data for tract 011000 (178/179)
Successfully fetched data for tract 011100 (179/179)

In [ ]:
# Displaying the final DataFrame `DC_CT_Education_2018` which contains 2018 ACS data
# for each specified census tract in Washington, D.C., including columns for
# census tract name and total population.

DC_CT_Education_2018.head(10)

,Census Tract Name,"Population 18 to 24 years, Less than high school graduate","Population 18 to 24 years, High school graduate (includes equivalency)","Population 18 to 24 years, Some college or associate's degree","Population 18 to 24 years, Bachelor's degree or higher","Population 25 years and over, Less than 9th grade","Population 25 years and over, 9th to 12th grade, no diploma","Population 25 years and over, High school graduate (includes equivalency)","Population 25 years and over, Some college, no degree","Population 25 years and over, Associate's degree","Population 25 years and over, Bachelor's degree","Population 25 years and over, Graduate or professional degree",state,county,tract
0,"Census Tract 1, District of Columbia, District...",1,8,131,132,110,0,160,144,0,1288,2297,11,001,000100
1,"Census Tract 2.01, District of Columbia, Distr...",0,916,2767,30,0,0,0,0,0,25,5,11,001,000201
2,"Census Tract 2.02, District of Columbia, Distr...",10,139,1304,155,0,9,15,156,64,729,1590,11,001,000202
3,"Census Tract 3, District of Columbia, District...",23,61,340,725,0,24,158,131,62,1510,2348,11,001,000300
4,"Census Tract 4, District of Columbia, District...",20,6,9,26,47,0,88,59,4,339,564,11,001,000400
5,"Census Tract 5.01, District of Columbia, Distr...",0,2,35,122,26,1,58,121,31,819,1896,11,001,000501
6,"Census Tract 5.02, District of Columbia, Distr...",35,35,23,128,8,10,101,159,31,834,1559,11,001,000502
7,"Census Tract 6, District of Columbia, District...",0,55,68,272,51,50,190,104,50,1035,2302,11,001,000600
8,"Census Tract 7.01, District of Columbia, Distr...",29,61,192,257,56,1,118,175,0,1432,3030,11,001,000701
9,"Census Tract 7.02, District of Columbia, Distr...",2,0,162,166,35,122,167,403,15,655,1439,11,001,000702

## Exploring and Customizing ACS Variable Metadata with Flexible Filtering

These two cells allow users to fetch, filter, and explore metadata for variables in the American Community Survey (ACS) dataset. By adjusting the variable codes (e.g., "S1501" or a specific variable like "S1501_C01_001E"), users can target and retrieve metadata for different ACS tables or individual variables, making this approach versatile for various analyses.


### Fetching and Filtering Metadata for a Specific Variable Table (e.g., S1501)

1. **URL Definition**: Sets the `metadata_url` to the Census API endpoint, providing access to metadata for all variables available in the 2022 ACS 5-Year Subject tables.

2. **Data Request**: Sends a request to retrieve JSON metadata on all ACS variables.

3. **Response Check**: If the request is successful (`status_code == 200`), the response data is stored as `variables_data`.

4. **Customizable Filtering for Variable Tables**: The code filters variables by looking for a specific table prefix (like "S1501"), allowing you to easily switch tables by changing this prefix. The result is stored in `S1501_variables`.

5. **Display of Variable Labels**: The filtered variables are printed with each variable's code and label, providing an overview of variables in the selected table.

**Output**: This displays each variable within the chosen table (e.g., S1501) with a brief description, facilitating easy identification of relevant variables. Users can change the table prefix (e.g., to "S1901" or "B17001") to explore different data tables.

In [ ]:
def get_table_variables(table_code):
    # Define the URL for the variable metadata
    metadata_url = "https://api.census.gov/data/2022/acs/acs5/subject/variables.json"

    # Send a request to the metadata endpoint
    response = requests.get(metadata_url)

    # Check if the response is successful
    if response.status_code == 200:
        variables_data = response.json()
        variables_list = variables_data["variables"]

        # Filter for variables that belong to the specified table code
        table_variables = {k: v for k, v in variables_list.items() if table_code in k}

        # Print out each variable and its label
        print(f"{table_code} Variables:")
        for var_code, details in table_variables.items():
            print(f"{var_code}: {details['label']}")
    else:
        print(f"Error fetching metadata: {response.status_code}")

# Example usage:
get_table_variables("S1501")  # Change "S1901" to any other table code to search for a different table

S1501 Variables:
S1501_C02_007E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade
S1501_C02_008E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma
S1501_C02_005E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher
S1501_C02_006E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over
S1501_C02_003E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)
S1501_C02_004E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree
S1501_C02_001E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years
S1501_C02_002E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate
S1501_C02_009E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)
S1501_C02_019E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years
S1501_C02_017E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher
S1501_C02_018E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher
S1501_C02_015E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher
S1501_C02_016E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years
S1501_C02_013E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree
S1501_C02_014E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher
S1501_C02_011E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree
S1501_C02_012E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree
S1501_C02_010E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree
S1501_C02_029E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!High school graduate or higher
S1501_C02_027E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher
S1501_C02_028E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone
S1501_C02_025E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over
S1501_C02_026E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher
S1501_C02_023E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher
S1501_C02_024E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher
S1501_C02_021E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher
S1501_C02_022E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years
S1501_C02_020E: Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher
S1501_C02_039E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!Bachelor's degree or higher
S1501_C02_037E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone
S1501_C02_038E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!High school graduate or higher
S1501_C02_035E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!High school graduate or higher
S1501_C02_036E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!Bachelor's degree or higher
S1501_C02_033E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!Bachelor's degree or higher
S1501_C02_034E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone
S1501_C02_031E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino
S1501_C02_032E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!High school graduate or higher
S1501_C02_030E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher
S1501_C02_040E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone
S1501_C02_049E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races
S1501_C02_047E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!High school graduate or higher
S1501_C02_048E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!Bachelor's degree or higher
S1501_C02_045E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!Bachelor's degree or higher
S1501_C02_046E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone
S1501_C02_043E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone
S1501_C02_044E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!High school graduate or higher
S1501_C02_041E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!High school graduate or higher
S1501_C02_042E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!Bachelor's degree or higher
S1501_C02_051E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!Bachelor's degree or higher
S1501_C02_052E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin
S1501_C02_050E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!High school graduate or higher
S1501_C02_059E: Estimate!!Percent!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings
S1501_C02_057E: Estimate!!Percent!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree
S1501_C02_058E: Estimate!!Percent!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher
S1501_C02_055E: Estimate!!Percent!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate
S1501_C02_056E: Estimate!!Percent!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)
S1501_C02_053E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!High school graduate or higher
S1501_C02_054E: Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!Bachelor's degree or higher
S1501_C02_063E: Estimate!!Percent!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Bachelor's degree
S1501_C02_064E: Estimate!!Percent!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree
S1501_C02_061E: Estimate!!Percent!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!High school graduate (includes equivalency)
S1501_C02_062E: Estimate!!Percent!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Some college or associate's degree
S1501_C02_060E: Estimate!!Percent!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Less than high school graduate
S1501_C06_009E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)
S1501_C06_006E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over
S1501_C06_005E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher
S1501_C06_008E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma
S1501_C06_007E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade
S1501_C06_014E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher
S1501_C06_013E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree
S1501_C06_016E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years
S1501_C06_015E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher
S1501_C06_010E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree
S1501_C06_012E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree
S1501_C06_011E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree
S1501_C06_018E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher
S1501_C06_017E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher
S1501_C06_019E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years
S1501_C06_020E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher
S1501_C06_026E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher
S1501_C06_025E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over
S1501_C06_028E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone
S1501_C06_027E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher
S1501_C06_022E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years
S1501_C06_021E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher
S1501_C06_024E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher
S1501_C06_023E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher
S1501_C06_002E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate
S1501_C06_001E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years
S1501_C06_004E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree
S1501_C06_003E: Estimate!!Percent Female!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)
S1501_C06_054E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!Bachelor's degree or higher
S1501_C06_053E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!High school graduate or higher
S1501_C06_056E: Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)
S1501_C06_055E: Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate
S1501_C06_050E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!High school graduate or higher
S1501_C06_052E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin
S1501_C06_051E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!Bachelor's degree or higher
S1501_C06_058E: Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher
S1501_C06_057E: Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree
S1501_C06_059E: Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings
S1501_C06_060E: Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Less than high school graduate
S1501_C06_062E: Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Some college or associate's degree
S1501_C06_061E: Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!High school graduate (includes equivalency)
S1501_C06_064E: Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree
S1501_C06_063E: Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Bachelor's degree
S1501_C06_029E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!High school graduate or higher
S1501_C06_030E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher
S1501_C06_032E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!High school graduate or higher
S1501_C06_031E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino
S1501_C06_038E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!High school graduate or higher
S1501_C06_037E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone
S1501_C06_039E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!Bachelor's degree or higher
S1501_C06_034E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone
S1501_C06_033E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!Bachelor's degree or higher
S1501_C06_036E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!Bachelor's degree or higher
S1501_C06_035E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!High school graduate or higher
S1501_C06_042E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!Bachelor's degree or higher
S1501_C06_041E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!High school graduate or higher
S1501_C06_044E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!High school graduate or higher
S1501_C06_043E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone
S1501_C06_040E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone
S1501_C06_049E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races
S1501_C06_046E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone
S1501_C06_045E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!Bachelor's degree or higher
S1501_C06_048E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!Bachelor's degree or higher
S1501_C06_047E: Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!High school graduate or higher
S1501_C04_041E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!High school graduate or higher
S1501_C04_042E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!Bachelor's degree or higher
S1501_C04_040E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone
S1501_C04_045E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!Bachelor's degree or higher
S1501_C04_046E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone
S1501_C04_043E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone
S1501_C04_044E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!High school graduate or higher
S1501_C04_049E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races
S1501_C04_047E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!High school graduate or higher
S1501_C04_048E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!Bachelor's degree or higher
S1501_C04_030E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher
S1501_C04_033E: Estimate!!Percent Male!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!Bachelor's degree or higher

### Searching for Specific Variable Metadata by Code

1. **Function Definition**: Defines the `search_specific_variable` function, which accepts a variable code (e.g., "S1501_C01_013E") to search for metadata on that specific variable.

2. **Data Request**: Similar to Cell 1, the function retrieves JSON metadata for all variables.

3. **Targeted Variable Search**: If the request is successful, the function checks if the specified `variable_code` is present in `variables_list`. If found, the function prints its label and concept, providing context for the variable’s role in the ACS dataset.

4. **Error Handling**: If the variable is not found or the request fails, the function outputs an error message.

**Usage**: This function provides detailed metadata for a specific variable by code, which can be customized simply by changing the `variable_code` input, enabling flexible and targeted metadata exploration.

In [ ]:
def search_specific_variable(variable_code):
    # Define the URL for the variable metadata
    metadata_url = "https://api.census.gov/data/2022/acs/acs5/subject/variables.json"

    # Send a request to the metadata endpoint
    response = requests.get(metadata_url)

    # Check if the response is successful
    if response.status_code == 200:
        variables_data = response.json()
        variables_list = variables_data["variables"]

        # Check if the variable code exists and print its details
        if variable_code in variables_list:
            details = variables_list[variable_code]
            print(f"{variable_code}: {details['label']}")
            print(f"Concept: {details['concept']}")
        else:
            print(f"Variable code {variable_code} not found.")
    else:
        print(f"Error fetching metadata: {response.status_code}")

# Example usage:
search_specific_variable("S1501_C01_013E")

S1501_C01_013E: Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree
Concept: Educational Attainment